development:
  adapter: mysql2
  database: net
  user: root
  password: "111"
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: net_test
  user: root
  password: "111"
  pool: 5
  timeout: 5000